In [ ]:
import numpy as np

featureMaps = [
    [[3,4,7], [5,6,1], [1,8,12]],
    [[6,12,10], [0,21,13], [17,9,19]],
]

featureMaps = np.array(featureMaps);

print("****************** INPUT TO FLATTEN LAYER ******************")

for i, featureMap in enumerate(featureMaps):
    print("\nFeature Map " + str(i + 1) + " : \n" + str(featureMap))

flattenOutput = featureMaps.flatten()

print("\n\n****************** OUTPUT OF FLATTEN LAYER ******************")

print("\nFlattened Layer Output: \n" + str(flattenOutput), end = "\n\n")

****************** INPUT TO FLATTEN LAYER ******************

Feature Map 1 : 
[[ 3  4  7]
 [ 5  6  1]
 [ 1  8 12]]

Feature Map 2 : 
[[ 6 12 10]
 [ 0 21 13]
 [17  9 19]]


****************** OUTPUT OF FLATTEN LAYER ******************

Flattened Layer Output: 
[ 3  4  7  5  6  1  1  8 12  6 12 10  0 21 13 17  9 19]



In [ ]:
# Loop 5 times, but we don't need to use the loop variable
for _ in range(1,20):
    print(_,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [ ]:
# List of items
items = ["apple", "banana", "cherry"]

# Loop through the list, but we don't need to use the actual items
for _ in items:
    print("Processing an item...")


Processing an item...
Processing an item...
Processing an item...


In [ ]:
# List of tuples, where each tuple contains two elements
coordinates = [(1, 2), (3, 4), (5, 6)]

# Loop through the list and unpack each tuple into i and j
for i, j in coordinates:
    print(f"X: {i}, Y: {j}")


X: 1, Y: 2
X: 3, Y: 4
X: 5, Y: 6


In [ ]:
# Dictionary with key-value pairs
person = {"name": "Alice", "age": 30, "city": "New York"}

# Loop through the dictionary and unpack each key-value pair into i and j
for i, j in person.items():
    print(f"{i}: {j}")


name: Alice
age: 30
city: New York


In [ ]:
# List of items
fruits = ["apple", "banana", "cherry"]

# Loop through the list with index and value using enumerate()
for i, j in enumerate(fruits):
    print(f"Index: {i}, Fruit: {j}")


Index: 0, Fruit: apple
Index: 1, Fruit: banana
Index: 2, Fruit: cherry
