In [14]:
import torch

single_tensor = torch.tensor([1],dtype=torch.float64)
single_tensor

tensor([1.], dtype=torch.float64)

In [16]:
tensor2 = torch.tensor([1,2,3,4])
tensor2

tensor([1, 2, 3, 4])

In [17]:
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)
    print (x)
else:
    print ("MPS device not found.")

tensor([1.], device='mps:0')


In [18]:
mps_device = torch.device("mps")
data = torch.tensor(1,device=mps_device)
print(data)
data.device

tensor(1, device='mps:0')


device(type='mps', index=0)